version: '3.8'
services:
  app:
    build: .
    volumes:
      - ./config.json:/app/config.json
  db:
    image: mongo:6
    environment:
      MONGO_INITDB_ROOT_USERNAME: myuser
      MONGO_INITDB_ROOT_PASSWORD: mypassword